// Generated by: pnpm dlx supabase gen types typescript --local > lib/supabase/types.ts
// Re-generate after schema changes with the command above.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      bookings: {
        Row: {
          id: string
          stay_id: string
          user_id: string
          check_in: string
          check_out: string
          guests: number
          total_price: number
          contact_name: string
          contact_email: string
          contact_phone: string | null
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          stay_id: string
          user_id: string
          check_in: string
          check_out: string
          guests: number
          total_price: number
          contact_name: string
          contact_email: string
          contact_phone?: string | null
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          stay_id?: string
          user_id?: string
          check_in?: string
          check_out?: string
          guests?: number
          total_price?: number
          contact_name?: string
          contact_email?: string
          contact_phone?: string | null
          status?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "bookings_stay_id_fkey"
            columns: ["stay_id"]
            isOneToOne: false
            referencedRelation: "stays"
            referencedColumns: ["id"]
          },
        ]
      }
      collection_stays: {
        Row: {
          collection_id: string
          stay_id: string
          position: number
        }
        Insert: {
          collection_id: string
          stay_id: string
          position?: number
        }
        Update: {
          collection_id?: string
          stay_id?: string
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: "collection_stays_collection_id_fkey"
            columns: ["collection_id"]
            isOneToOne: false
            referencedRelation: "collections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "collection_stays_stay_id_fkey"
            columns: ["stay_id"]
            isOneToOne: false
            referencedRelation: "stays"
            referencedColumns: ["id"]
          },
        ]
      }
      collections: {
        Row: {
          id: string
          title: string
          slug: string
          description: string | null
          created_at: string
        }
        Insert: {
          id?: string
          title: string
          slug: string
          description?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          description?: string | null
          created_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      reviews: {
        Row: {
          id: string
          stay_id: string
          user_id: string
          rating: number
          comment: string | null
          created_at: string
        }
        Insert: {
          id?: string
          stay_id: string
          user_id: string
          rating: number
          comment?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          stay_id?: string
          user_id?: string
          rating?: number
          comment?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reviews_stay_id_fkey"
            columns: ["stay_id"]
            isOneToOne: false
            referencedRelation: "stays"
            referencedColumns: ["id"]
          },
        ]
      }
      stays: {
        Row: {
          id: string
          title: string
          slug: string
          description: string
          location: string
          price_per_night: number
          cleaning_fee: number
          service_fee: number
          max_guests: number
          type: string
          vibe: string
          travel_type: string
          amenities: string[]
          images: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          slug: string
          description: string
          location: string
          price_per_night: number
          cleaning_fee?: number
          service_fee?: number
          max_guests?: number
          type: string
          vibe: string
          travel_type: string
          amenities?: string[]
          images: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          description?: string
          location?: string
          price_per_night?: number
          cleaning_fee?: number
          service_fee?: number
          max_guests?: number
          type?: string
          vibe?: string
          travel_type?: string
          amenities?: string[]
          images?: string[]
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Convenience type helpers
type PublicSchema = Database["public"]
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type InsertTables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type UpdateTables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
